apiVersion: apps/v1
kind: Deployment
metadata:
  name: salmatextile-app-deployment
  namespace: dev
  labels:
    app: salmatextile-app
spec:
  replicas: 3

  selector:
    matchLabels:
      app: salmatextile-app

  template:
    metadata:
      labels:
        app: salmatextile-app

    spec:
      containers:
        - name: salmatextile-app
          image: "docuser1122/salmatextile-app:latest"
          imagePullPolicy: IfNotPresent

          command:
            - sh
            - -c

          args:
            - |
              sleep 15 &&
              php artisan migrate --force &&
              php artisan db:seed --force &&
              php artisan serve --host=0.0.0.0 --port=8000

          ports:
            - containerPort: 8000
